server:
  port: 7100

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7005/eureka,http://eureka2.com:7006/eureka  #集群版
      #defaultZone: http://localhost:7001/eureka
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    hostname: localhost

zuul:
  routes:
    users:
      path: /**
#      url: http://localhost:8020/user/
      serviceId: eureka-provider
