server:
  port: ${BSY_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
    shutdown:
      enabled: true
spring:
  application:
    name: apiservice

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${BSY_SERVER_IP}
    instance-id: ${spring.application.name}:${BSY_SERVER_IP}:${server.port}
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka  #单机版
      defaultZone: ${BSY_EUREKA_ZONE}
