server:
  port: 12345

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
    shutdown:
      enabled: true
spring:
  application:
    name: apicall

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.83
    instance-id: ${spring.application.name}:192.168.1.83:12345
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka  #单机版
      defaultZone: http://192.168.1.188:7001/eureka,http://192.168.1.188:7002/eureka #集群版
