server:
  port: ${BSY_SERVER_PORT}

spring:
  application:
    name: eureka

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: ${BSY_EUREKA_NAME}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${BSY_SERVER_IP}:${server.port}
  client:
    #false表示自己端就是注册中心,职责是维护实例,并不需要检索服务
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #设置与Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: ${BSY_EUREKA_ZONE}
    #        defaultZone: http://eureka7002.com:7002/eureka/  #集群指向其他eureka
  server:
      # 关闭自我保护机制，保证不可用服务被及时剔除.默认开启保护机制 true
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000

